# Generated by Django 3.2.6 on 2021-08-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0002_auto_20210824_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='brand_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='sustainecho_django_api.citybrand'),
        ),
    ]
