# Generated by Django 3.2.6 on 2021-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0004_auto_20210824_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='brand_list',
        ),
    ]
