# Generated by Django 3.2.6 on 2021-08-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0006_city_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='sustainecho_django_api.brand'),
        ),
    ]
