# Generated by Django 3.2.6 on 2021-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0007_alter_city_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='employee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
