# Generated by Django 3.2.6 on 2021-08-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0010_brand_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='sustainecho_django_api.city'),
        ),
    ]
