# Generated by Django 3.2.6 on 2021-08-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0011_alter_brand_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['employee_count']},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='duration',
            new_name='employee_count',
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('city', 'employee_count')},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='order',
        ),
    ]
