# Generated by Django 3.2.6 on 2021-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0012_auto_20210824_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
