# Generated by Django 3.2.6 on 2021-08-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainecho_django_api', '0013_auto_20210824_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
    ]
